version: 2.1
jobs:
  upload:
    docker:
    - image: circleci/openjdk:11.0.12
    steps:
    - checkout
    - run:
        name: Create security ring
        command: echo -n "${SIGN_KEY}" | base64 --decode > secring
    - run:
        name: Upload artifacts
        command: ./gradlew uploadArchives
    - run:
        name: Close and Promote
        command: ./gradlew closeAndReleaseRepository --debug --stacktrace
  test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
workflows:
  test:
    jobs:
    - test
  release-artifacts:
    jobs:
    - test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+\.[0-9]+\.[0-9]+/
    - upload:
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+\.[0-9]+\.[0-9]+/
